bank_app/main/routes.py
from flask import render_template,Blueprint

main=Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html')



bank_app/services/routes.py
from flask import (render_template,flash,redirect,url_for
                   ,request,session,Blueprint)
from bank_app.models import User,Transactions
from flask_login import current_user,login_required
from bank_app import app
from bank_app.services.forms import WithdrawForm,DepositForm
from bank_app.services.utils import sent_otp_email


services=Blueprint('services',__name__)


@services.route("/transactions",methods=['GET','POST'])
@login_required
def transactions():
    page = request.args.get('page', 1, type=int)
    per_page = 5
    user = Transactions.query.filter_by(user_id=current_user.id).paginate(page=page, per_page=per_page)
    image_file=url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('transactions.html',image_file=image_file,user=user)

@services.route("/withdraw",methods=['GET','POST'])
def withdraw():
    form=WithdrawForm()
    if form.validate_on_submit():
        user=User.query.filter_by(pin=form.pin.data).first()
        if user:
            session['withdrawal_amount'] = form.withdraw.data
            sent_otp_email(user)
            return redirect(url_for('verify_otp_withdraw'))
        else:
            flash('Pin Is Invalid. Please check your Four Digit Pin.','danger')
    image_file=url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('withdraw.html',image_file=image_file,form=form)


@services.route("/deposit",methods=['GET','POST'])
def deposit():
    form=DepositForm()
    if form.validate_on_submit():
        user=User.query.filter_by(pin=form.pin.data).first()
        if user:
            session['deposit_amount'] = form.deposit.data
            sent_otp_email(user)
            return redirect(url_for('verify_otp_deposit'))
        else:
            flash('Pin Is Invalid. Please check your Four Digit Pin.','danger')
    image_file=url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('deposit.html',image_file=image_file,form=form)

bank_app/users/routes.py
from flask import (render_template,flash,redirect,
                   url_for,request,session,Blueprint)
from bank_app.models import User,Transactions
from flask_login import login_user,current_user,logout_user,login_required
from bank_app import db,bcrypt
from bank_app.users.forms import (RegistrationFrom,LoginFrom,UpdateAccountForm,
                                  RequestResetForm,ResetPasswordForm)
from bank_app.users.utils import sent_reset_email,save_picture
import random


users=Blueprint('users',__name__)


@users.route("/register",methods=['GET','POST'])
def register():
    form=RegistrationFrom()
    if form.validate_on_submit():
        hashed_password= bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,
                    acc_type=form.acc_type.data,account_no=random.randint(100000, 999999),
                    aaahaar_no=form.aadhaar_number.data,image_file='default.jpg',
                pin=form.pin.data,balance=form.deposit.data,password=hashed_password)
        
        db.session.add(user)
        db.session.commit()
        flash(f'Account created!','success')
        login_user(user)
        trans=Transactions(account_no=current_user.account_no,balance=form.deposit.data,
                            deposit=form.deposit.data,withdraw=0.0,author=current_user)
        db.session.add(trans)
        db.session.commit()
        
        return redirect(url_for('users.account_info'))
    return render_template('register.html',title='Register',form=form) 



@users.route("/login",methods=['GET','POST'])
def login():
    form=LoginFrom()
    if form.validate_on_submit():
        user=User.query.filter_by(account_no=form.acc_no.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            next_page=request.args.get('next')
            if next_page:
                return redirect(url_for(next_page))
            else :
                flash('You Have logged into your account.','success')
                return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessfull. Please check your Account Number and password','danger')
    return render_template('login.html',title='Login',form=form)

@users.route("/logout",methods=['GET','POST'])
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/update",methods=['GET','POST'])
@login_required
def update():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file 
            db.session.commit()
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('acccount has been updated','success')
        return redirect(url_for('users.account_info'))
    elif request.method=='GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
    image_file=url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('update.html',title='Update', 
                        image_file=image_file,form=form)


@users.route("/account_info",methods=['GET','POST'])
@login_required
def account_info():
    user = current_user
    image_file=url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('account_info.html',image_file=image_file,user=user)


@users.route("/reset_password",methods=['GET','POST'])
def reset_request():
    form=RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user:
            sent_reset_email(user)
            flash('An Email Is Sent To you Email ID....','info')
            return redirect(url_for('main.home'))
    return render_template('reset_request.html',title='Reset Password',form=form)

@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):
    user=User.verify_reset_token(token)
    if user is None:
        flash("Invalid or Expired Token",'warning')
        return redirect(url_for('users.reset_request'))
    form=ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password= bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash(f'Pin Has Been Updated!','success')
        return redirect(url_for('main.home'))

    return render_template('reset_token.html',title='Reset Pin',form=form)


bank_app/templates/about.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <h1 class="display-4 mb-4">About Flask Bank App</h1>
    <p>
        Flask Bank App is a simple web application built with Flask, a lightweight web framework in Python. It allows users to manage their bank accounts online, perform transactions, and check their account balance and transaction history.
    </p>
    
</div>
{% endblock %}

bank_app/templates/account_info.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
  <legend class="border-bottom mb-4">Account Info</legend>

  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}" alt="Profile Image">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <h2>Account No: {{ current_user.account_no }}</h2>
      <div class="mt-4">
        <h5 class="mb-3">Account Type: {{ user.acc_type }}</h5>
        <h5 class="mb-3">Aaahaar Number: {{ user.aaahaar_no }}</h5>
        <h5 class="mb-3">Email: {{ user.email }}</h5>
        <h5 class="mb-3">Pin: {{ user.pin }}</h5>
        <h5 class="mb-3">Balance-- {{ user.balance }} Ruppees</h5>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bank_app/templates/deposit.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{current_user.username}}</h2>
        <h3>Account_No -- {{current_user.account_no}}</h3>
        <p class="text-secondary">{{current_user.email}}</p>
      </div>
    </div>
    <!-- FORM HERE -->
    
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Deposit Amount</legend>
            
            <div class="form-group">
                {{ form.deposit.label (class="form-control=label")}}
                {% if form.deposit.errors %} 
                    {{ form.deposit(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.deposit.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                <input class="form-control form-control-lg" name="deposit" placeholder="Enter The Amount">
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.pin.label(class="form-control-label") }}
                {% if form.pin.errors %} 
                    {{ form.pin(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.pin.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                <input type="password" class="form-control form-control-lg" name="pin" placeholder="Enter The PIN">
                {% endif %}
            </div>
            
            
            
            
        </fieldset>
        <div class="form-group">
        {{ form.submit (class="btn btn-outline-info") }}
        </div>
        <samll>
            <a href="{{url_for('users.reset_request')}}"> Forgot Pin?</a>
        </samll>
    </form>
      
      

    
</div>
{% endblock content %}

bank_app/templates/home.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <h1 class="display-4 mb-4">Welcome to Flask Bank App!</h1>
    <p  class="home-paragraph">
        This is the home page of our Bank App. You can view your account information, deposit and withdraw money, and perform various banking transactions using this app.
    </p>
    {% if current_user.is_authenticated %}
    <p  class="home-paragraph">
        You are currently logged in as  <strong>{{ current_user.username }}</strong>. You can access your account details and other features through the navigation bar above.
    </p>
    {% else %}
    <p  class="home-paragraph">
        If you are an existing user, you can log in to your account or if you are a new user, you can register to create an account and access our banking services.
    </p>
    {% endif %}
</div>
{% endblock %}

bank_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles.css') }}"> 
    
    {% if title %}
    <title>Flask Blog-- {{title}}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
</head>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Bank App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('services.deposit')}}">Deposit</a>
                <a class="nav-item nav-link" href="{{ url_for('services.withdraw')}}">Withdraw</a>
                <a class="nav-item nav-link" href="{{ url_for('services.transactions')}}">Transaction</a>
                
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.update')}}">Update</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account_info')}}">Account Info</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>  
                <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>

      <main role="main" class="container">
        <div class="row">
          <div class="col-md-9">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category,message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-3">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcement</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
</body>
</html> 

bank_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login Into Your Account</legend>
                
                <div class="form-group">
                    {{ form.acc_no.label(class="form-control-label") }}
                    {% if form.acc_no.errors %} 
                        {{ form.acc_no(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.acc_no.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="acc_no" placeholder="Enter The Account Number">
                    {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }} 
                    {% if form.password.errors %} 
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input type="password" class="form-control form-control-lg" name="password" placeholder="Enter The Account Password">
                    {% endif %}
                </div>
                <div class="form-group">
                     {{ form.remember(class="btn btn-outline-info") }}
                     {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
            </div>
            <samll>
                <a href="{{url_for('users.register')}}"> Forgot Password?</a>
            </samll>
        </form>
        
    </div>
    <div class ="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register')}}">Sign Up Now</a>
        </small>

    </div>
    
{% endblock content %}

bank_app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=>
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Your Account</legend>
                
                <div class="form-group">
                    {{ form.username.label (class="form-control-label")}}
                    {% if form.username.errors %} 
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="username" placeholder="Enter The Name">
                    {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="email" placeholder="Enter Your Email ID">
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.aadhaar_number.label(class="form-control=label") }} 
                    {% if form.aadhaar_number.errors %} 
                        {{ form.aadhaar_number(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.aadhaar_number.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="aaahaar_no" placeholder="Enter Your Aadhaar Number">
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.acc_type.label(class="form-control=label") }}
                    {% if form.acc_type.errors %}
                        {{ form.acc_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.acc_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.acc_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.deposit.label (class="form-control=label")}}
                    {% if form.deposit.errors %} 
                        {{ form.deposit(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.deposit.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="deposit" placeholder="Enter The Amount To Be Deposited">
                    {% endif %}
                </div>
    
                <div class="form-group">
                    {{ form.pin.label (class="form-control=label")}}
                    {% if form.pin.errors %} 
                        {{ form.pin(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.pin.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="pin" placeholder="Enter PIN">
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control=label") }} 
                    {% if form.password.errors %} 
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input type="password" class="form-control form-control-lg" name="password" placeholder="Enter The Passowrd">
                    {% endif %}
                </div>
                
                <div class="form-group">
                {{ form.confirm_password.label(class="form-control=label")  }}
                    {% if form.confirm_password.errors %} 
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input type="password" class="form-control form-control-lg" name="confirm_password" placeholder="ReEnter The Password">
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
            </div>
        </form>
        
        

    </div>
    <div class ="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login')}}">Sign IN</a>
        </small>

    </div>
    
{% endblock content %}

bank_app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Passowrd</legend>
                
                <div>
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input class="form-control form-control-lg" name="email" placeholder="Enter The Email">
                    {% endif %}
                </div>
                
               
            </fieldset>
            <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

bank_app/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Passowrd</legend>
                
                <div>
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %} 
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input type="password" class="form-control form-control-lg" name="password" placeholder="Enter The Passowrd">
                    {% endif %}
                </div>
                <div>
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %} 
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    <input type="password" class="form-control form-control-lg" name="confirm_password" placeholder="ReEnter The Password">
                    {% endif %}
                </div>
                
               
            </fieldset>
            <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

bank_app/templates/transactions.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
  <legend class="border-bottom mb-4">Account Info</legend>

  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}" alt="Profile Image">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <h2>Account No: {{ current_user.account_no }}</h2>
      <div class="mt-4">
        <h5 class="mb-3">Account Type  -- {{ current_user.acc_type }}</h5>
        <h5 class="mb-3">Aadhaar Number -- {{ current_user.aaahaar_no }}</h5>
        <h5 class="mb-3">Current Balance -- {{ current_user.balance }} Ruppees</h5>
      </div>
    </div>
  </div>

  <hr>

  <h3 class="mb-3">Transactions</h3>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Date Of Transaction</th>
        <th>Deposit</th>
        <th>Withdraw</th>
        <th>Balance</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in user %}
        <tr>
          <td class="column-spacing">{{ loop.index  }}</td>
          <td class="column-spacing">{{ transaction.date_posted }}</td>
          <td class="column-spacing">{{ transaction.deposit }}</td>
          <td class="column-spacing">{{ transaction.withdraw }}</td>
          <td class="column-spacing">{{ transaction.balance }}</td>
        </tr>
      {% endfor %}
    </tbody>
    
  </table>
  <!-- Pagination -->
    <div class="pagination">
        {% for page_num in user.iter_pages( left_edge=1 ,right_edge=1 ,left_current=1 ,right_current=2 ) %}
        {% if page_num %}
          {% if user.page==page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('services.transactions',page=page_num)}}">{{ page_num }}</a>
          {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('services.transactions',page=page_num)}}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
  
      {% endfor %}
    </div>
</div>
{% endblock %}